name: Build Zerotier Dev
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    name: Build and push to registry
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@v3

      - name: Environment Vars setup
        run: |
          echo "zt_version_latest=$(git describe --tags `git rev-list --tags --max-count=1`)" >> "$GITHUB_ENV"
          echo "zt_version=$(git describe --abbrev=0)" >> "$GITHUB_ENV"
          echo "zt_dev_sha=$(git ls-remote https://github.com/zerotier/ZeroTierOne.git --head refs/heads/dev | awk '{print $1}')" >> "$GITHUB_ENV"

      - name: Tar as root
        run: |
          sudo mv -fv /usr/bin/tar /usr/bin/tar.orig
          echo -e '#!/bin/sh\n\nsudo /usr/bin/tar.orig "$@"' | sudo tee -a /usr/bin/tar
          sudo chmod +x /usr/bin/tar

      - name: Enable caching for podman
        id: cache-podman-restore
        uses: actions/cache/restore@v3
        with:
          path: |
            ~/.local/share/containers
          key: ${{ runner.os }}-zerotier-docker

      - name: Log in to Quay
        uses: redhat-actions/podman-login@v1
        with:
          registry: "quay.io"
          username: ${{ secrets.ZENITH_QUAY_USER }}
          password: ${{ secrets.ZENITH_QUAY_TOKEN }}

      - name: Log in to registry.redhat.io
        uses: redhat-actions/podman-login@v1
        with:
          registry: "registry.redhat.io"
          username: ${{ secrets.ZENITH_REDHAT_USER }}
          password: ${{ secrets.ZENITH_REDHAT_TOKEN }}
      
      - name: Podman Socket
        run: |
          podman system service  --time=0 unix:///tmp/podman.sock &

      - name: Build container for UBI - Origin branch dev
        id: build-dev
        uses: redhat-actions/buildah-build@v2
        with:
          image: zerotier-docker
          tags: dev
          layers: true
          containerfiles: |
            ./Dockerfile
          build-args: |
            zt_version=dev

      - name: Build container for UBI - Origin branch dev - sha commit
        id: build-sha
        uses: redhat-actions/buildah-build@v2
        with:
          image: zerotier-docker
          tags: ${{ env.zt_dev_sha }}
          layers: true
          containerfiles: |
            ./Dockerfile
          build-args: |
            zt_version=dev
            quay_expiration=1w

      - name: Build container for Debian - Origin branch dev
        id: build-dev-debian
        uses: redhat-actions/buildah-build@v2
        with:
          image: zerotier-docker
          tags: dev-debian
          layers: true
          containerfiles: |
            ./Dockerfile.debian
          build-args: |
            zt_version=dev

      - name: Build container for Debian - Origin branch dev - sha commit
        id: build-sha-debian
        uses: redhat-actions/buildah-build@v2
        with:
          image: zerotier-docker
          tags: ${{ env.zt_dev_sha }}-debian
          layers: true
          containerfiles: |
            ./Dockerfile.debian
          build-args: |
            zt_version=dev
            quay_expiration=1w

      - name: Push to Quay - Origin branch dev
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-dev.outputs.image }}
          tags: ${{ steps.build-dev.outputs.tags }}
          registry: quay.io/zenithtecnologia

      - name: Push to Quay - Origin branch dev - sha commit
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-sha.outputs.image }}
          tags: ${{ steps.build-sha.outputs.tags }}
          registry: quay.io/zenithtecnologia

      - name: Push to Quay Debian - Origin branch dev
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-dev-debian.outputs.image }}
          tags: ${{ steps.build-dev-debian.outputs.tags }}
          registry: quay.io/zenithtecnologia

      - name: Push to Quay Debian - Origin branch dev - sha commit
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-sha-debian.outputs.image }}
          tags: ${{ steps.build-sha-debian.outputs.tags }}
          registry: quay.io/zenithtecnologia

      - name: Update caching for podman
        uses: actions/cache/save@v3
        with:
          path: |
            ~/.local/share/containers
          key: ${{ steps.cache-podman-restore.outputs.cache-primary-key }}

      - name: Run Trivy vulnerability scanner - Origin branch dev
        run: |
          podman run --privileged -v /tmp/podman.sock:/var/run/docker.sock -v ./:/data docker.io/aquasec/trivy:latest image --quiet --format sarif --output /data/zerotier-docker-ubi.sarif --exit-code 1 --severity CRITICAL,HIGH --vuln-type os,library --ignore-unfixed ${{ steps.build-dev.outputs.image }}

#      - name: Run Trivy vulnerability scanner - Debian origin branch dev
#        run: |
#          podman run --privileged -v /tmp/podman.sock:/var/run/docker.sock -v ./:/data docker.io/aquasec/trivy:latest image --quiet --format sarif --output /data/zerotier-docker-debian.sarif --exit-code 1 --severity CRITICAL,HIGH --vuln-type os,library --ignore-unfixed ${{ steps.build-dev-debian.outputs.image }}

      - name: Upload Trivy scan results to GitHub Security tab - UBI
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'zerotier-docker-ubi.sarif'

#      - name: Upload Trivy scan results to GitHub Security tab - UBI
#        uses: github/codeql-action/upload-sarif@v2
#        with:
#          sarif_file: 'zerotier-docker-debian.sarif'

      - name: Update caching for podman
        uses: actions/cache/save@v3
        with:
          path: |
            ~/.local/share/containers
          key: ${{ steps.cache-podman-restore.outputs.cache-primary-key }}
